baseURL = "https://kenlayisalive.org/"
languageCode = 'en-us'
title = 'Kenlay is Alive'

theme = "ananke"

[outputFormats]
  [outputFormats.SITEMAP]
    baseName = "sitemap"
    isPlainText = true
    mediaType = "application/xml"
    notAlternative = true
  [outputFormats.POSTSITEMAP]
    baseName = "post-sitemap"
    isPlainText = true
    mediaType = "application/xml"
    notAlternative = true

[mediaTypes]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputs]
  home = ["HTML", "RSS", "SITEMAP", "POSTSITEMAP"]
